# -*- coding: utf-8 -*-
"""Project_Sinthia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rRHWj345veXVwyNYRT5GZIn1VWORXUVa
"""

import tkinter as tk
from tkinter import messagebox

def encrypt(text): # Modified encrypt function to accept text as input
    if not text:
        messagebox.showerror("Error", "Please enter valid text!")
        return
    encrypted_text = ' '.join(format(ord(char), '08b') for char in text)
    return f"Encrypted Binary: {encrypted_text}" # Return the encrypted text

def decrypt(binary_text): # Modified decrypt function to accept binary text as input
    if not binary_text or not all(c in "01 " for c in binary_text):
        messagebox.showerror("Error", "Please enter valid binary text!")
        return
    try:
        decrypted_text = ''.join(
            chr(int(binary_chunk, 2))
            for binary_chunk in binary_text.split()
        )
        return f"Decrypted Text: {decrypted_text}" # Return the decrypted text
    except ValueError:
        messagebox.showerror("Error", "Invalid binary input!")

# Now to use these functions, just call them with your inputs

example_text = "Hello"
encrypted_result = encrypt(example_text)
print(encrypted_result)

example_binary = "01001000 01100101 01101100 01101100 01101111"
decrypted_result = decrypt(example_binary)
print(decrypted_result)

